### ISSUE TITLE
SI IBAN prefix

### ISSUE THREAD

**Issue by Prome88** [figo-connect/schwifty#5]
The specifications for SI IBAN are technically correct, but in reality the central bank of Slovenia uses only 56 as the "2!n" part after SI. Consiquently all IBANs start with SI56 - see the [link](https://www.bsi.si/en/payment-systems.asp?MapaId=1502) for more info.

**Comment by mdomke** [comment]
As far as I read the documentation from the link you provided the checksum digits are still calculated conforming to the IBAN specification. My assumption is that the BBAN specific checksum is computed in a way, so that the IBAN check digits are always 56. Is that correct?
Nevertheless I'm not sure from your issue description if there is actually a problem with the implementation. If so could you please elaborate what your problem actually is?

**Comment by mdomke** [comment]
Ping @Prome88

**Comment by Prome88** [comment]
Hi,
as im quite new to github, I've mistakenly open an issue instead of an forum thread.

Yes you are correct, maybe it would be clearer with the example from [wikipedia](ur=https://en.wikipedia.org/wiki/International_Bank_Account_Number):

SI**kk** bbss sccc cccc cxx

k = IBAN check digits (**always = "56"**)
b = National bank code
s = Branch code
c = Account number
x = National check digits

Few countries do not utilize the IBAN in full and have some fixed numbers / characters, usually as IBAN check digits.

The question is if IBAN.generate() supports / will support this deviation(s)/addendum(s) from IBAN standard?

**Comment by berend** [comment]
Getting BICs from the bank code of an IBAN is not done via some algorithm. It is a fixed list, where you have to lookup the bank code (that is part of the IBAN). We implemented that for Germany, since there is an official source that is more or less machine readable. You can have a look how that is done in this repository [here](https://github.com/figo-connect/schwifty/tree/master/scripts).

If there is such a list to get a mapping bank code to BIC for all slowenian banks, let us know or create a pull requests.

We looked into this a while back, but there where no good sources for this kind of information.

**Comment by berend** [comment]
Also, back to topic on @Prome88 issue - let my the to understand your problem:

Slowenian IBANs consist of `SIkk bbss sccc cccc cxx` where `xx` is a checksum for the BBAN part of the IBAN (meaning `bbss sccc cccc cxx`, so that the `kk` IBAN checksum is always 56.

And you want to generate a IBAN by just having National bank code (`b`), branch code (`s`) and the account number (`c`), but not the internal checksum (`x`).

Is that correct?

Is there a source on the algorithm, that is behind that checksum?

**Comment by Prome88** [comment]
Central bank of Slovenia has this list available from:
https://www.bsi.si/placila-in-infrastruktura/placilne-storitve-in-elektronski-denar/identifikacijske-oznake-in-kode-bic

**Comment by berend** [comment]
The list of BICs is appreciated, thanks! It is not as machine readable as it could be (.csv, .json or .xml), but at least - a list!

Regarding generation of the BBAN checksums, I did not find any algorithm on the website you linked, also not on linked webpages (in slowenian) like [this one ](http://www.pisrs.si/Pis.web/pregledPredpisa?id=SKLE10989#), but _the_ php lib for handling IBANs has the same issue [here](https://github.com/globalcitizen/php-iban/issues/39) (open for over 2 years). It contains some resources - and as far as I could see also the wanted algorithm for Slowenia.

I draw two conclusions here:

* it is a lot of work
* we should base the work here on their collected list
* help is welcome!


@Prome88 Did i understand your problem correctly (two comments up)?

**Comment by kdolinar** [comment]
Hi, let me post a follow-up on this matter. The algorithm is specified (albeit in Slovene language), if you follow some of the links above to an official law amendment. To spare you the inconvenience, let me briefly sketch the algorithm:

First of all you should know that each slovene BBAN is suffixed with two control digits so that modulo 97 you will always get 1. So BBAN % 97 = 1 always.

IBAN validation:
1. Take BBAN and concatenate to get the following string: BBAN<S><I>00 (here <S> = "28" and <I> = "18"). 
2. Divide the resulting number by modulo 97. As BBAN % 97 = 1, then BBAN<S><I>00 % 97 is always constant, namely 57.
3. Replace 00 at the end with control digits 56 and you will always get BBAN<S><I>56 % 97 = 1.

Hence, in order to get a valid IBAN, you should always use 56 as control digits in the "SEPA header" (right after the country code) for every slovene IBAN.

Of course, in order to facilitate a full-fledged BBAN validation, a special functional block should be added to Schwifty to manipulate IBANS by their corresponding BBAN validation algorithm, which is frankly speaking a lot of work. However, as a slightly better approximation of a full SI IBAN validation, a simple modification of SEPA specification »SI2!n5!n8!n2!n« can be made by using the right control digits 56 instead of 2!n. 

So, put at least »SI565!n8!n2!n« and you'll be slightly better off with Slovene IBAN validation. In fact, I have created a pull request https://github.com/figo-connect/schwifty/pull/12 with this modification and some other improvements of the Schwifty internal IBAN spec JSON DB. Please review ...

**Comment by mdomke** [comment]
Fixed by #12
